const borderData=[
    {
        id:1,
        img:"/images/br1.png"
    },
    {
        id:2,
        img:"/images/br2.png"
    },
    {
        id:3,
        img:"/images/br3.png"
    },
    {
        id:4,
        img:"/images/br4.png"
    },
    {
        id:5,
        img:"/images/br5.png"
    },
    {
        id:6,
        img:"/images/br1.png"
    },
    {
        id:7,
        img:"/images/br2.png"
    },
    {
        id:8,
        img:"/images/br3.png"
    },
    {
        id:9,
        img:"/images/br4.png"
    },
    {
        id:10,
        img:"/images/br5.png"
    },
]
export default borderData;