const colorData = [
    {
        id:1,
        img:"images/red.png"
    },
    {
        id:2,
        img:"images/yellow.png"
    },
    {
        id:3,
        img:"images/silver.png"
    },
    {
        id:4,
        img:"images/pink.png"
    },
    {
        id:5,
        img:"images/orange.png"
    },
    {
        id:6,
        img:"images/green.png"
    },
    {
        id:7,
        img:"images/red.png"
    },
    {
        id:8,
        img:"images/pink.png"
    },
    {
        id:9,
        img:"images/green.png"
    },
    {
        id:10,
        img:"images/yellow.png"
    },
    {
        id:10,
        img:"images/yellow.png"
    },
    {
        id:10,
        img:"images/yellow.png"
    },
];
export default colorData