const merchantData=[
    {  id:1,
        img:"/images/mer1.png",
    },
    {  id:2,
        img:"https://cdn.shopify.com/s/files/1/0560/2227/0115/products/12_4_txqnzttspqqzmqf2_400x.jpg?v=1618919323",
    },
    {  id:7,
        img:"/images/mer2.png",
    },
    {  id:3,
        img:"/images/mer3.png",
    },
    {  id:4,
        img:"/images/mer4.png",
    },
    {  id:4,
        img:"/images/mer4.png",
    },
    {  id:4,
        img:"/images/mer4.png",
    },
    {  id:4,
        img:"/images/mer4.png",
    },
    {  id:4,
        img:"/images/mer4.png",
    },
    {  id:4,
        img:"/images/mer4.png",
    },
    {  id:4,
        img:"/images/mer4.png",
    },
    {  id:4,
        img:"/images/mer4.png",
    },
    {  id:4,
        img:"/images/mer4.png",
    },
    {  id:4,
        img:"/images/mer4.png",
    },
    {  id:4,
        img:"/images/mer4.png",
    },
    {  id:4,
        img:"/images/mer4.png",
    },
    {  id:4,
        img:"/images/mer4.png",
    },
    {  id:4,
        img:"/images/mer4.png",
    },
    
]

export default merchantData;