const picData=[
    
    {
        id:1,
        img:"/images/pic1.png",
    },
    {
        id:2,
        img:"/images/pic2.png",
    },
    {
        id:3,
        img:"/images/pic3.png",
    },
    {
        id:4,
        img:"/images/pic4.png",
    },
    {
        id:5,
        img:"/images/pic5.png",
    },
    {
        id:6,
        img:"/images/pic6.png",
    },
    {
        id:7,
        img:"/images/pic2.png",
    },
    {
        id:8,
        img:"/images/pic5.png",
    },
    {
        id:9,
        img:"/images/pic5.png",
    },
    {
        id:9,
        img:"/images/pic5.png",
    },
    {
        id:9,
        img:"/images/pic5.png",
    },
    {
        id:9,
        img:"/images/pic5.png",
    },
    {
        id:9,
        img:"/images/pic5.png",
    },
    {
        id:9,
        img:"/images/pic5.png",
    },
    {
        id:9,
        img:"/images/pic5.png",
    },
    {
        id:9,
        img:"/images/pic5.png",
    },
    {
        id:9,
        img:"/images/pic5.png",
    },
    {
        id:9,
        img:"/images/pic5.png",
    },
    {
        id:9,
        img:"/images/pic5.png",
    },
    {
        id:9,
        img:"/images/pic5.png",
    },
    {
        id:9,
        img:"/images/pic5.png",
    },
]
export default picData;